---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: suihei
  name: apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      containers:
        - name: apiserver
          image: oreandawe/redis-queue-monitor-worker:latest
          imagePullPolicy: IfNotPresent
          command:
            - gunicorn
            - --bind
            - 0.0.0.0:2000
            - --access-logfile
            - "-"  # Print to stdout
            - --capture-output
            # - --logger-class
            # - somepkg.SomeClass
            - app:create_apiserver_app()
          ports:
            - containerPort: 2000
          env:
            - name: REDIS_HOST
              value: redis-server
            - name: REDIS_PORT
              value: "36379"

---
apiVersion: v1
kind: Service
metadata:
  namespace: suihei
  name: apiserver
spec:
  type: NodePort
  ports:
    - port: 32000
      nodePort: 32000
      protocol: TCP
      targetPort: 2000
  selector:
    app: apiserver