---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      containers:
        - name: apiserver
          # https://github.com/zannen/redis-queue-monitor-worker/
          image: oreandawe/redis-queue-monitor-worker:latest
          imagePullPolicy: IfNotPresent
          command:
            - gunicorn
            - --bind
            - 0.0.0.0:2000
            - --access-logfile
            - "-"  # Print to stdout
            - --capture-output
            - app:create_apiserver_app()
          ports:
            - containerPort: 2000
          env:
            - name: REDIS_HOST
              value: "redis-server.{{ .Release.Namespace }}.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"

---
apiVersion: v1
kind: Service
metadata:
  name: apiserver
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.customMetrics.apiServer.port }}
      nodePort: {{ .Values.customMetrics.apiServer.port }}
      protocol: TCP
      targetPort: 2000
  selector:
    app: apiserver