# See /licensing.md for licence details.
---
apiVersion: v1
kind: Secret
metadata:
  name: cm-adapter-serving-certs
  namespace: {{ .Release.Namespace }}
data:
  serving.crt: {{ .Values.customMetrics.servingCert }}
  serving.key: {{ .Values.customMetrics.servingKey }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-metrics-apiserver
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-metrics-apiserver
  template:
    metadata:
      labels:
        app: custom-metrics-apiserver
      name: custom-metrics-apiserver
    spec:
      containers:
        - name: custom-metrics-apiserver
          # https://github.com/zannen/redis-queue-monitor-worker/
          image: oreandawe/redis-queue-monitor-worker:latest
          imagePullPolicy: IfNotPresent
          command:
            - gunicorn
            - --bind
            - 0.0.0.0:6443
            - --access-logfile
            - "-"  # Print to stdout
            - --capture-output
            - --keyfile
            - /var/run/serving-cert/serving.key
            - --certfile
            - /var/run/serving-cert/serving.crt
            - app:create_metrics_exporter_app()
          ports:
            - containerPort: 6443
          volumeMounts:
            - mountPath: /var/run/serving-cert
              name: volume-serving-cert
              readOnly: true
      volumes:
        - name: volume-serving-cert
          secret:
            secretName: cm-adapter-serving-certs

---
apiVersion: v1
kind: Service
metadata:
  name: custom-metrics-apiserver
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 6443
  selector:
    app: custom-metrics-apiserver

{{ if .Values.customMetrics.apiService.deploy }}
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
spec:
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#apiservicespec-v1-apiregistration-k8s-io
  caBundle: {{ .Values.customMetrics.apiService.caBundle }}
  service:
    name: custom-metrics-apiserver
    namespace: {{ .Release.Namespace }}
  group: custom.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
{{ end }} # if .Values.customMetrics.apiService.deploy
