# See /licensing.md for licence details.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-metrics-apiserver
  namespace: suihei
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-metrics-apiserver
  template:
    metadata:
      labels:
        app: custom-metrics-apiserver
      name: custom-metrics-apiserver
    spec:
      serviceAccountName: custom-metrics-apiserver
      containers:
        - name: custom-metrics-apiserver
          # https://github.com/kubernetes-sigs/prometheus-adapter
          image: k8s.gcr.io/prometheus-adapter/prometheus-adapter:v0.9.1  # use k8s.gcr.io for tags >v0.8.4
          # OLD: image: quay.io/coreos/k8s-prometheus-adapter-amd64:v0.4.1  # use quay.io for tags <=v0.8.4
          args:
            - /adapter
            - --secure-port=6443
            - --tls-cert-file=/var/run/serving-cert/serving.crt
            - --tls-private-key-file=/var/run/serving-cert/serving.key
            - --logtostderr=true
            - --prometheus-url=http://prometheus:9090/
            - --metrics-relist-interval=30s
            - --v=10  # verbosity
            - --config=/etc/adapter/config.yaml
          ports:
            - containerPort: 6443
          volumeMounts:
            - mountPath: /var/run/serving-cert
              name: volume-serving-cert
              readOnly: true
            - mountPath: /etc/adapter/
              name: config
              readOnly: true
      volumes:
        - name: volume-serving-cert
          secret:
            secretName: cm-adapter-serving-certs
        - name: config
          configMap:
            name: adapter-config
