# See /licensing.md for licence details.
---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
spec:
  service:
    name: custom-metrics-apiserver
    namespace: suihei
    # port: 443
  group: custom.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100

### can't get v1 to work.
# kubectl get apiservice | grep metrics
# v1.custom.metrics.k8s.io  suihei/custom-metrics-apiserver  False (FailedDiscoveryCheck)

# ---
# apiVersion: apiregistration.k8s.io/v1
# kind: APIService
# metadata:
#   name: v1.custom.metrics.k8s.io  # must be `spec.version + "." + spec.group`
# spec:
#   # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#apiservicespec-v1-apiregistration-k8s-io
#   # caBundle: ""  # If unspecified, system trust roots on the apiserver are used.
#   group: custom.metrics.k8s.io
#   groupPriorityMinimum: 100
#   insecureSkipTLSVerify: true
#   service:
#     name: custom-metrics-apiserver
#     namespace: suihei
#   version: v1
#   versionPriority: 100
