# See /licensing.md for licence details.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-metrics-resource-reader
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - namespaces
      - pods
      - services
    verbs:
      - get
      - watch
      - list
