# See /licensing.md for licence details.
---
apiVersion: v1
kind: Service
metadata:
  name: custom-metrics-apiserver
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 6443
  selector:
    app: custom-metrics-apiserver
