# See /licensing.md for licence details.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-metrics-apiserver
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-metrics-apiserver
  template:
    metadata:
      labels:
        app: custom-metrics-apiserver
      name: custom-metrics-apiserver
    spec:
      containers:
        - name: custom-metrics-apiserver
          # https://github.com/zannen/redis-queue-monitor-worker/
          image: oreandawe/redis-queue-monitor-worker:latest
          imagePullPolicy: IfNotPresent
          command:
            - gunicorn
            - --bind
            - 0.0.0.0:6443
            - --access-logfile
            - "-"  # Print to stdout
            - --capture-output
            - --keyfile
            - /var/run/serving-cert/serving.key
            - --certfile
            - /var/run/serving-cert/serving.crt
            - app:create_metrics_exporter_app()
          ports:
            - containerPort: 6443
          env:
            - name: REDIS_HOST
              value: redis-server
            - name: REDIS_PORT
              value: "36379"
          volumeMounts:
            - mountPath: /var/run/serving-cert
              name: volume-serving-cert
              readOnly: true
      volumes:
        - name: volume-serving-cert
          secret:
            secretName: cm-adapter-serving-certs

---
apiVersion: v1
kind: Secret
metadata:
  name: cm-adapter-serving-certs
  namespace: {{ .Release.Namespace }}
data:
  serving.crt: {{ .Values.customMetrics.servingCert }}
  serving.key: {{ .Values.customMetrics.servingKey }}
