---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: suihei
  name: rq-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rq-monitor
  template:
    metadata:
      labels:
        app: rq-monitor
    spec:
      containers:
        - name: rq-monitor
          image: oreandawe/redis-queue-monitor-worker:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2000
          env:
            - name: REDIS_HOST
              value: redis-server
            - name: REDIS_PORT
              value: "36379"

---
apiVersion: v1
kind: Service
metadata:
  namespace: suihei
  name: rq-monitor
spec:
  type: NodePort
  ports:
    - port: 32000
      nodePort: 32000
      protocol: TCP
      targetPort: 2000
  selector:
    app: rq-monitor
