---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rq-worker
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rq-worker
  template:
    metadata:
      labels:
        app: rq-worker
    spec:
      containers:
        - name: rq-worker
          # https://github.com/zannen/redis-queue-monitor-worker/
          image: oreandawe/redis-queue-monitor-worker:latest
          imagePullPolicy: IfNotPresent
          command:
            - rq
            - worker
            - high  # queue name
            - low  # queue name
            - -w
            # For app.MyWorker, see:
            # https://github.com/zannen/redis-queue-monitor-worker/blob/main/app/__init__.py
            - app.MyWorker
            - --url
            - redis://redis-server:36379
