# v1:
# - see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#horizontalpodautoscalerspec-v1-autoscaling
# - has "targetCPUUtilizationPercentage" only

# v2beta2:
# - see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#horizontalpodautoscalerspec-v2beta2-autoscaling
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: rq-worker-high-hpa
  namespace: suihei
spec:
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#horizontalpodautoscalerspec-v2beta2-autoscaling
  # behavior:
  #   scaleDown:
  #     # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#hpascalingpolicy-v2beta2-autoscaling
  #     policies: []
  #     selectPolicy: "MaxPolicySelect"
  #     stabilizationWindowSeconds: 60
  #   scaleUp:
  #     policies: []
  #     selectPolicy: "MaxPolicySelect"
  #     stabilizationWindowSeconds: 60
  metrics:
    # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#metricspec-v2beta2-autoscaling
    # - type: Object
    #   object:
    #     describedObject:
    #       apiVersion: apps/v1
    #       kind: Deployment
    #       name: rq-worker-high
    #     # GET /apis/custom.metrics.k8s.io/v1beta1/namespaces/suihei/deployments.apps/rq-worker-high/redisqueue_length?metricLabelSelector=wiggle%3Dwobble
    #     metric:
    #       name: redisqueue_length
    #       # selector:
    #       #   matchExpressions:
    #       #     - key: ""
    #       #       operator: ""
    #       #       values: []
    #       #   matchLabels:
    #       #     # dict of K:V pairs, equivalent to matchExpressions with {key:K, operator:"In", values:[V]}
    #       #     wiggle: wobble
    #     target:
    #       # averageUtilization: 0  # only valid for Resource metric source
    #       # averageValue: 1  # averaged across all pods
    #       type: Value
    #       value: 1
    - type: Pods
      pods:
        metric:
          name: redisqueue_length
          # selector: ...
        target:
          type: AverageValue
          averageValue: 1
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rq-worker-high
