---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: rq-worker-high-hpa
  namespace: suihei
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rq-worker-high
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          # see https://github.com/zannen/redis-queue-monitor-worker/blob/main/app/__init__.py#L104-L120
          name: yourappnamehere_redis_queue_length
        target:
          type: AverageValue
          averageValue: 1
