---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: rq-worker-high-hpa
  namespace: suihei
spec:
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#horizontalpodautoscalerspec-v2beta2-autoscaling
  metrics:
    - type: Object
      object:
        describedObject:
          apiVersion: apps/v1
          kind: Deployment
          name: rq-worker-high
        # GET /apis/custom.metrics.k8s.io/v1beta1/namespaces/NAMESPACE/deployments.apps/APP/METRIC?metricLabelSelector=KEY%3DVALUE
        metric:
          name: redisqueue_length
          selector:
            matchLabels:
              queue: high
        target:
          type: Value
          value: 1
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rq-worker-high
